[build]
  functions = "netlify-functions"  # Directory where your serverless functions are located

[[plugins]]
  package = "@netlify/plugin-functions-core"  # Optional, for handling serverless functions
